### ISSUE TITLE
Make sclang path configurable

### ISSUE THREAD

**Issue by bagong** [supercollider/scvim#22]
Hi,

it seems to run sclang in a non-standard install location (e.g. in userspace) you have to find bin/scpipe/lib/sc/pipe.rb and edit that file.

Would be nice if the sclang path could be set in .vimrc (or can it, and I just overlooked the option?)

Thanks
.r.

**Comment by carlocapocasa** [comment]
No, it cannot- but you can add your custom sclang directory to your path, for example by editing your ~/.profile file, adding this line:

export PATH=/directory/that/contains/sclang:$PATH

Then close and reopen your terminal and type `which sclang`. If you get the right sclang, it should work in scvim too.

Having said that, hardcoded paths are a nuisance, and more configurability is better than less, so I will keep this as a low priority issue because it's a little bit annoying but not critical.

**Comment by bagong** [comment]
Thanks!

**Comment by carlocapocasa** [comment]
Absolutely!
