### ISSUE TITLE
sbl/scvim 

### ISSUE THREAD

**Issue by sbl** [supercollider/scvim#7]
Hi everybody!

I just wanted to mention that I have been maintaining a scvim plugin for quite some time (before supercollider moved to github) , that you can find over here - also based on the original scvim work.

https://github.com/sbl/scvim

Some rework has gone in it and different people have contributed and used it over the time. Happy to move that over here to have one unified place for a scvim plugin. Why don't you try it out and see if it makes sense to merge both efforts.

Best
Stephen

**Comment by dvzrv** [comment]
hey @sbl!
What exactly has changed between this version and yours?
Have you tried a diff of this version and yours? Some work has been done on scvim when it was still part of the SuperCollider repository, too.
Careful merging would be nice, I guess.

**Comment by blacksound** [comment]
I've been testing the sbl fork now.
From my experience, and looking at the code I would think that the sbl/scvim fork would be a better starting point for further development of scvim.
 I looked over the diff across the forks and I can't really see that there are much of the commits in the current supercolider/scvim repo that needs to be merged. Please correct me if I'm wrong.
It makes much more sense to have sbl/scvim as a starting point for further develpment.

So I propose that we change the supercollider/scvim to fork the sbl/supercollider repo instead of the (imho) stale version that is currently bundled with supercollider.

What do people think about this?

**Comment by kisielk** [comment]
I'm +1 to this. It would also reduce the confusion for new Vim users, less maintenance, etc.
